export const educations = [
  {
    id: '1',
    title: 'Technologist in Systems Analysis and Development',
    university: 'Fatec Rubens Lara',
    period: 'JAN 2020 - PRESENT',
    tags: [
      'Software Development',
      'C',
      'C++',
      'Java',
      'Design Patterns',
      'OOP',
      'UML',
      'SQL',
      'DevOps',
      'Database',
    ],
  },
  {
    id: '2',
    title: 'Technician in Systems Development',
    university: 'ETEC Doutora Ruth Cardoso',
    period: 'AGO 2019 - DEC 2020',
    tags: [
      'Software Development',
      'HTML',
      'CSS',
      'TypeScript',
      'JavaScript',
      'JQuery',
      'PHP',
      'Ionic',
      'Bootstrap',
      'SQL',
      'Database',
    ],
  },
];
